sudo: false
dist: trusty
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libfreetype6-dev
    - libjpeg8-dev
    - libx11-dev
    - libxrandr-dev
    - libx11-xcb-dev
    - libxcb-randr0-dev
    - libxcb-image0-dev
    - libgl1-mesa-dev
    - libsndfile1-dev
    - libopenal-dev
    - libpthread-stubs0-dev
    - g++-8

# credits to Sam Legrand
before_install:
- mkdir cmake-dist
- mkdir sfml-dev
- travis_retry wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz | sudo tar --strip-components=1 -C sfml-dev -xvf
- export PATH=$PWD/SFML/bin:$PATH;
- travis_retry wget -qO- https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz | sudo tar --strip-components=1 -C cmake-dist -xz 
- export PATH=$PWD/cmake-dist/bin:$PATH;

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi

script:
  - mkdir build
  - cd build
  - gcc -v && g++ -v && cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
