sudo: false
dist: trusty
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

# credits to Sam Legrand
before_install:
- mkdir cmake-dist
- travis_retry wget -qO- https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz | sudo tar --strip-components=1 -C cmake-dist -xz 
- export PATH=$PWD/cmake-dist/bin:$PATH;
- mkdir sfml-dist
- travis_retry wget -qo- http://www.sfml-dev.org/files/SFML-2.3-linux-gcc-64-bit.tar.gz | sudo tar --strip-components=1 -C sfml-dist -xz
- export PATH=$PWD/sfml-dist/:$PATH;


install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi

script:
  - mkdir build
  - cd build
  - gcc -v && g++ -v && cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
